---
galaxy_info:
  author: Gewers Homelab
  description: Perform dist-upgrades, reboot if required, and autoremove old packages on Debian-based systems.
  company: Gewers Homelab
  license: BSD-3-Clause
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - bookworm
        - bullseye
    - name: Ubuntu
      versions:
        - focal
        - jammy
dependencies: []
