---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Pull required container images
      community.docker.docker_image:
        name: "{{ item.image }}"
        source: pull
      loop: "{{ molecule_yml.platforms }}"

    - name: Ensure Molecule instance(s) are running
      community.docker.docker_container:
        name: "{{ item.name }}"
        hostname: "{{ item.name }}"
        image: "{{ item.image }}"
        state: started
        recreate: true
        command: {{ item.command | default(omit) }}
        privileged: {{ item.privileged | default(false) }}
        tty: {{ item.tty | default(false) }}
        env: {{ item.environment | default({}) }}
        volumes: {{ item.volumes | default([]) }}
        tmpfs: {{ item.tmpfs | default([]) }}
      loop: "{{ molecule_yml.platforms }}"
      register: server

    - name: Build instance configuration
      ansible.builtin.set_fact:
        instance_conf: "{{ (instance_conf | default([])) + [
          {
            'instance': item.item.name,
            'address': item.item.address | default(item.item.name),
            'user': item.item.ansible_user | default('root'),
            'port': item.item.ansible_port | default('22'),
            'identity_file': item.item.identity_file | default('')
          }
        ] }}"
      loop: "{{ server.results }}"

    - name: Dump instance config
      ansible.builtin.copy:
        content: |
          # Molecule managed

          {{ instance_conf | to_json | from_json | to_yaml }}
        dest: "{{ molecule_instance_config }}"
        mode: "0600"
