---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  # no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Stop and remove Molecule instance(s)
      community.docker.docker_container:
        name: "{{ item.name }}"
        state: absent
        force_kill: true
      loop: "{{ molecule_yml.platforms }}"

    - name: Reset instance config
      ansible.builtin.copy:
        content: |
          # Molecule managed

          []
        dest: "{{ molecule_instance_config }}"
        mode: "0600"
