---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: maintenance-instance
    image: ghcr.io/geerlingguy/docker-ubuntu2204-ansible:latest
    command: /lib/systemd/systemd
    privileged: true
    tty: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    environment:
      container: docker

provisioner:
  name: ansible
  inventory:
    host_vars:
      maintenance-instance:
        ansible_connection: community.docker.docker
        ansible_python_interpreter: /usr/bin/python3

verifier:
  name: ansible
