---
dependency:
  name: galaxy
  options:
    requirements-file: ../../collections/requirements.yml
driver:
  name: delegated
platforms:
  - name: instance
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
  inventory:
    hosts:
      all:
        hosts:
          instance:
            ansible_connection: local
            ansible_python_interpreter: "{{ ansible_playbook_python }}"
verifier:
  name: ansible
