---
dependency:
  name: galaxy
  options:
    requirements-file: ../../collections/requirements.yml
driver:
  name: docker
platforms:
  - name: instance
    image: quay.io/ansible/ubuntu-systemd:jammy
    pre_build_image: true
    privileged: true
    command: /usr/sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /tmp
    environment:
      container: docker
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
  inventory:
    hosts:
      all:
        hosts:
          instance:
            ansible_connection: docker
            ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
