---
# Minimal galaxy.yml for a playbook project for tools to recognize this as a collection

namespace: "gewers"
name: "homelab"
readme: README.md
version: 0.0.1
authors:
  - your name <example@domain.com> # TO-DO: update with your name and email

description: Collection for gewers.homelab playbook project

# TO-DO: update the tags based on your content type
tags: ["tools"]

repository: NA
