name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible molecule "molecule-plugins[delegated]"

      - name: Install Ansible collections
        run: ansible-galaxy collection install -r collections/requirements.yml --force

      - name: Run Molecule tests
        run: molecule test -s linux
